### ISSUE TITLE
Multiple TAG_RESOLVE_FAILED YAML Warnings when Running Stack Finder

### ISSUE THREAD

**Issue by daniel-h-88** [cdklabs/awscdk-v1-stack-finder#34]
Hello, 

I have a customer who is trying to run the Stack Finder tool to identify CDK v1 stacks. When they try to run the Stack Finder tool as described in the documentation, they encountered multiple warnings that follow this format: `[TAG_RESOLVE_FAILED] YAMLWarning`.

An example of this error from my own testing in my lab environment can be found below:

`(node:33755) [TAG_RESOLVE_FAILED] YAMLWarning: Unresolved tag: !Ref at line 281, column 18:
            Value: !Ref AWSSupportPatchworkVersion
`

This happens over and over again on different intrinsic functions, such as `!Ref`, `!Join`, `!Sub`, etc.

In the end, I get this output:

``` 
YAMLParseError: Flow map in block collection must be sufficiently indented and end with a } at line 622, column 9:

        PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
        ^

    at Composer.onError (/XXX/XXX/.npm/_npx/1a70b0cb204f1c57/node_modules/yaml/dist/compose/composer.js:69:34)
    at Object.resolveFlowCollection (/XXX/XXX/.npm/_npx/1a70b0cb204f1c57/node_modules/yaml/dist/compose/resolve-flow-collection.js:182:9)
    at Object.composeCollection (/XXX/XXX/.npm/_npx/1a70b0cb204f1c57/node_modules/yaml/dist/compose/compose-collection.js:21:42)
    at composeNode (/XXX/XXX/.npm/_npx/1a70b0cb204f1c57/node_modules/yaml/dist/compose/compose-node.js:31:38)
    at Object.resolveBlockMap (/XXX/XXX/.npm/_npx/1a70b0cb204f1c57/node_modules/yaml/dist/compose/resolve-block-map.js:79:19)
    at Object.composeCollection (/XXX/XXX/.npm/_npx/1a70b0cb204f1c57/node_modules/yaml/dist/compose/compose-collection.js:13:36)
    at composeNode (/XXX/XXX/.npm/_npx/1a70b0cb204f1c57/node_modules/yaml/dist/compose/compose-node.js:31:38)
    at Object.resolveBlockSeq (/XXX/XXX/.npm/_npx/1a70b0cb204f1c57/node_modules/yaml/dist/compose/resolve-block-seq.js:36:15)
    at Object.composeCollection (/XXX/XXX/.npm/_npx/1a70b0cb204f1c57/node_modules/yaml/dist/compose/compose-collection.js:17:36)
    at composeNode (/XXX/XXX/.npm/_npx/1a70b0cb204f1c57/node_modules/yaml/dist/compose/compose-node.js:31:38) {
  code: 'BAD_INDENT',
  pos: [ 24511, 24512 ],
  linePos: [ { line: 622, col: 9 }, { line: 622, col: 10 } ]
}

```

It is not clear to me from this error output which stack template in the parsing process is causing this YAMLParseError to occur.

Although my customer also experiences the `TAG_RESOLVE_FAILED` errors I described above, they experience a different error when it comes down to the stack trace output:

```
TypeError: Cannot read properties of undefined (reading 'split')
    at findV1Stacks (/XXX/XXX/.nvm/versions/node/v16.14.2/lib/node_modules/awscdk-v1-stack-finder/lib/index.js:149:85)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async processListStacksResponse (/XXX/XXX/.nvm/versions/node/v16.14.2/lib/node_modules/awscdk-v1-stack- finder/lib/index.js:122:5)
    at async find (/XXX/XXX/.nvm/versions/node/v16.14.2/lib/node_modules/awscdk-v1-stack-finder/lib/index.js:94:9)
```

Just as in my case, it is not obvious what templates are causing the problem. From just my glancing at how the program runs in my terminal, it seems it is happening on all of the templates the Stack Finder finds.

I had not used the Stack Finder myself in my lab environment prior to encountering this issue, so I am unaware of anything that may have changed in my environment that could be contributing to this issue.

Please let me know if I can provide any more information about this issue. I will help in any way I can. Thanks!

**Comment by madeline-k** [comment]
Hello @daniel-h-88, thank you for opening this issue! This tool uses the [yaml](https://www.npmjs.com/package/yaml) library to parse templates when they are not in yaml (in other words, when they fail to parse as JSON). So it looks like there might be some issue with that library not being able to parse your template. 

I just created this pull request: https://github.com/cdklabs/awscdk-v1-stack-finder/pull/39 to add better error logging in your scenario. After it is merged and released, can you try running it again? It should then print out the names of the stacks that are failing to parse. And then if you can provide the templates, that will help me diagnose further what is going on.

**Comment by daniel-h-88** [comment]
Hi Madeline,

I tried running the `npx awscdk-v1-stack-finder` command again but I still get the same `TAG_RESOLVE_FAILED` warnings for some of the templates, but I don't see the extra error messaging that you added in #39.

What is interesting is that if I do a global install of the Stack finder tool using `npm install -g awscdk-v1-stack-finder`, It installs 60 packages on my system, as can be seen here:

```
npm install -g awscdk-v1-stack-finder
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

added 60 packages, and audited 61 packages in 3s

```

After that, the `YAMLParseError` no longer occurs at the end of the Stack Finder output, although the `TAG_RESOLVE_FAILED` warnings are still present, and I still cannot see the added error messaging. 

After doing the global install, I do get output that says `No AWS CDK V1 Stacks found`, although I am pretty sure I do have some in my account, but perhaps some of these YAML parsing issues are preventing them from being recognized as V1 stacks?

Not quite sure what is going wrong here.

**Comment by barticus** [comment]
Can confirm that when ran via npx, errors are thrown for YAML templates using CloudFormation functions, e.g.

```
[TAG_RESOLVE_FAILED] YAMLWarning: Unresolved tag: !If at line 120, column 13
[TAG_RESOLVE_FAILED] YAMLWarning: Unresolved tag: !GetAtt at line 135, column 25
[TAG_RESOLVE_FAILED] YAMLWarning: Unresolved tag: !Sub at line 138, column 37
```

**Comment by diego-santacruz** [comment]
I am also getting tons of these `TAG_RESOLVE_FAILED` messages related to the CloudFormation intrinsics, which make it nearly impossible to digest the script output and I am not sure the identification is reliably given the number of warnings.

I do not think we have esoteric Cfn templates around, they are created either by CDK or by the serverless framework. One thing that we have are nested stacks though (created by the serverless framework), maybe that is the origin of the problem?
